### ISSUE TITLE
Cache pages instead of loading them new every time

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#263]
There is a lot of (sometimes very long) loading in the app. Maybe could figure out a way to cache them so that they load instantly after you've already loaded it once. The longer an app takes to load the less patience users are likely to have to use it.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/4406983/176022339-d1a0eb57-8f54-4da5-ba4c-aaf077a88940.png">

**Comment by sebastinez** [comment]
Yeah this is a big issue, the sometimes very long loading times are due to multiple calls to Alchemy, TheGraph and Ceramic.
We are working on a backend for radicle-interface which will eventually do a lot of fetching and rendering on the server, similar to what workstream does, so it should all be much faster.

**Comment by cloudhead** [comment]
Yeah tbh I'm not sure why the-graph is so freaking slow there. I think alchemy is performing fairly well in comparison? We can cache it before we have a backend. We can also get rid of the org listing for now as orgs v1 are deprecated.

**Comment by sebastinez** [comment]
PR #306 will close this issue for now
