### ISSUE TITLE
Image errors in markdown component

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#336]
Looks like something's wrong with the image handling of our markdown component:

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/40774/186255509-416b87f7-3af2-4d00-9eea-e151222d2d30.png">

URL: https://app.radicle.network/seeds/willow.radicle.garden/rad:git:hnrkbx9xzjg8tf9hj9uh5qdxwuyjddsxyaw6o/tree/ec825d8999538f110e572605dc56ef7bf44cc574

**Comment by sebastinez** [comment]
Ok it seems like we found an edge case here, since we haven't been using external images in READMEs.
It seems if we just check that we aren't trying to query an external URL (starting with `http`) from a repo we should be fine.

Here an idea
https://github.com/radicle-dev/radicle-interface/commit/b9ad93cbf8740355cffc9cba32f03c9355533ac5

**Comment by cloudhead** [comment]
yeah, I think that works.
