### ISSUE TITLE
Allow using middle mouse button to open a link in a new tab

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#378]
A common web usage pattern is to open links for later reading in separate tabs by clicking the middle mouse button or holding command/ctrl and left clicking. This currently doesn't work, because we're only handling the `on:click` event. We could potentially use also the `on:auxclick` event, but unfortunately that [doesn't work on Safari](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event#browser_compatibility).

If we're considering switching out the router, we should also think about how we could enable this functionality.

One potential way to pull this off it is to only use anchor tags (`<a href="#xxx>"`) and hash routing for navigation elements that are clickable. Then we wouldn't need to bother manually handling click events.

Here are a couple of areas in the app that I've tried middle-clicking out of habit and wondered why it didn't work:

<img width="1840" alt="Screenshot 2022-09-09 at 16 17 14" src="https://user-images.githubusercontent.com/158411/189371843-3f194e85-b7d5-497e-838a-27a802c5b2cc.png">
<img width="1840" alt="Screenshot 2022-09-09 at 16 17 30" src="https://user-images.githubusercontent.com/158411/189371866-28bfdd00-6bb5-41e0-9e39-560f72d8a04d.png">
<img width="1840" alt="Screenshot 2022-09-09 at 16 17 35" src="https://user-images.githubusercontent.com/158411/189371883-745444d4-4bf7-45db-a499-da2ef39f0409.png">
<img width="1840" alt="Screenshot 2022-09-09 at 16 19 36" src="https://user-images.githubusercontent.com/158411/189371890-9d9fd547-bbc5-4aa4-b4e5-9fb33667707a.png">

**Comment by sebastinez** [comment]
Interesting, I think that the hash routing would surely be a good way to go forward, since this would also allow us to host the web interface on IPFS.

Was initially thinking about providing hash routing only when needed e.g. in IPFS deployments, but if we could provide middle mouse button clicking by going for hash routing it would make sense.

Not entirely sure if I'm missing something that the current way of routing provides (besides the url schema) that we would miss.

**Comment by sebastinez** [comment]
Just for reference, hash routing is being worked on at #478
We should remember that this could be solved by using hash routing
