### ISSUE TITLE
Wizard for setting up a name for an Org

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#38]
Currently, setting up a new ENS name for an Org is a 3-step process:

1. Register the name at `/registrations`
2. Point the name to the org address, by editing the ENS records, at `/registrations/:name`
3. Set the name of the org to the registered name, at `/orgs/:address`

It would be nice to have a wizard that does these three steps in one flow, at `/orgs/:address/registration/wizard`.

This page could be linked from the Org success modal, after an org is created.

**Comment by sebastinez** [comment]
I had some time to think about how to implement this to avoid too much back and forth and keep it as simple as posible.

I propose to create a proxy component on the route `/orgs/:address/registration/wizard`, that would use the existing org name setting components i.e. `Registrations::New`, `Registrations:Submit` to be able to traverse through the name setting workflow, the persisting of the required information would be solved by implementing a writable Store, eg:

```ts
interface Wizard {
  state: State.NameRegistration; subdomain: string
  state: State.PointNameToOrgAddress; subdomain: string; address: string;
  state: State.SetNameOfOrg; subdomain: string; address: string
}
```
Here a simple flowchart to see the working and validations it would run during the wizard.
![Flowdiagram-Wizard](https://user-images.githubusercontent.com/7912302/125176569-caeaaf80-e1aa-11eb-9134-c71f88eae601.png)

For the components I suggest to add a `wizard` attribute, so we can alter the behavior of the required components without changing their behavior in the current use cases.
The behavior modifications would be eg. that instead of navigating to another route the wizard Store changes which would let to moving to the next step of the wizard.

**Comment by cloudhead** [comment]
The banner in #51 would actually kick-off this flow, so as discussed, I'll start with that, and we'll see where that leads!

**Comment by cloudhead** [comment]
Closing this as orgsV1 are being phased out.
