### ISSUE TITLE
Decentralize hosting and DNS

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#40]
* [ ] https://fleek.co/ or something for hosting
* [ ] ENS instead of DNS, using `app.radicle.eth`
* [ ] ens.link fallback?

**Comment by sebastinez** [comment]
@cloudhead would take this issue but don't know how you want to handle the user credentials, eg.: Fleek requires to login with GitHub OAuth..
I could build the page publish it to IPNS and offer it via my own IPFS node but I think you'll want something more cooked similar to Fleek.

Let me know if I can help here.

**Comment by sebastinez** [comment]
Okay after mounting pages on fleek for testing, I propose that:

- We open up an account on https://fleek.co and link the radicle-interface repo with it.
- After that we can link a ENS domain like app.radicle.eth on Fleek.
- And instead of using a dnslink fallback we can eventually work on using a handshake top level domain like `.radicle` and then create a `app.radicle` ?

**Comment by sebastinez** [comment]
Here some documentation on how we could use fleek to configurate ENS and eventually DNSLink or Handshake quick.

https://docs.fleek.co/domain-management/ens-domains/
https://docs.fleek.co/domain-management/hns-domains/
https://docs.fleek.co/domain-management/dns-link/
