### ISSUE TITLE
Connection hangs when wallet unlock is dismissed

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#52]
To reproduce:

1. Lock your metamask wallet, disconnect and refresh
2. Click connect
3. Close the window which asks for password unlock
4. See how the connect button hangs

**Comment by sebastinez** [comment]
Hmm I was able to reproduce this behavior, but I'm not sure if it's a bug or expected behavior..

If the user dismisses the password unlock, Metamask will still allow the user to unlock its wallet by clicking on the extension icon.
Whats the scenario that a user wants to connect but then dismisses the unlock procedure?

If we still want to be able to unfreeze the situation from the UI, we could eg.:
- Add a timeout, to abort the connect process after a specific amount of time.
- Allow the user to hover over the connect button and instead of Disconnect show eg. Cancel

**Comment by cloudhead** [comment]
The thing is, there *is* an error in the console when you dismiss the unlock window, I think it's an assertion that fails. So it could just be a matter of handling that case..

**Comment by sebastinez** [comment]
> The thing is, there *is* an error in the console when you dismiss the unlock window, I think it's an assertion that fails. So it could just be a matter of handling that case..

Interesting will check that and handle the case appropriately

**Comment by sebastinez** [comment]
> The thing is, there _is_ an error in the console when you dismiss the unlock window

Hmm do you have an example of the error message? I'm getting another error message, when doing your procedure but in the end I unlock Metamask and get the following error

```
Uncaught (in promise) Error: assertion failed
    at assert (error.ts:39)
    at Object.refreshBalance (session.ts:93)
    at t.exports.<anonymous> (session.ts:203)
```

It seems there is an issue when the `window.ethereum.on('accountsChanged')` fires, the connection state eventually did not arrive at `Connection.Connected` we can avoid that by checking if connection is equal to Connected similar to https://github.com/radicle-dev/radicle-interface/blob/8a6c2938a63a3f924d0a3c1de3dc536c3300e525/src/App.svelte#L19

**Comment by cloudhead** [comment]
That is actually the error I'm trying to hunt down - I thought it was caused by closing the unlock window :thinking:

**Comment by sebastinez** [comment]
Hmm with the new WalletConnect Modal it seems this bug is gone.
