### ISSUE TITLE
Star a project

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#63]
It would be nice to have a way of bookmarking / signaling interest in a project, like on github.

To avoid the spam issue, we could hide stars from users who don't have a radicle.eth name. Only they would see their own stars, but they wouldn't be visible publicly.

To avoid the tx fee issue we would use a signed message stored off-chain instead of a transaction. The question is where? Cermaic? IPFS? Sia?

**Comment by sebastinez** [comment]
> The question is where? Ceramic? IPFS? Sia?

@cloudhead I would suggest Ceramic since it will be a data structure that will eventually mutate quite often, and Sia and IPFS would work too with IPNS for example, but Ceramic is built for mutable streams of data and would eventually work great with the IDX user profiles.

Regarding the data structure, I'm in contact with the ceramic team, but IMO imI think the best way would be to have a kind of hashmap to link project URNs to a list of user signed messages.

**Comment by cloudhead** [comment]
Interesting, yeah. I think I concur.

Perhaps we could also have some backend running somewhere (that anyone can run), that indexes stars and provides the API needed by the frontend?

**Comment by sebastinez** [comment]
> Perhaps we could also have some backend running somewhere (that anyone can run), that indexes stars and provides the API needed by the frontend?

Yeah I this would be great, since we could index on one hand the projects a particular user has starred and on the other the amount of stars a particular project has.

**Comment by rudolfs** [comment]
Is this still relevant?

**Comment by sebastinez** [comment]
> Is this still relevant?

I think at some point it would be nice to have something like this, maybe can write it down in some roadmap, so we don't forget

**Comment by sebastinez** [comment]
I'll close this issue for now and we'll see from user feedback if this comes up at some point.
