### ISSUE TITLE
Registration doesn't load after name is registered

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#65]
An annoying caching issue: when the registration of a name is completed and you click "View", it sometimes goes to the page an shows "name not registered". This is probably caused by caching, either at the client level (hopefully?) or at the server level. We could retry or have a spinner until it loads, or find a way to disable caching for that request.

**Comment by sebastinez** [comment]
Okay I did some tries and I couldn't reproduce the bug..

It seems to me that ethers.js is not using any cache with its queries, so I can only imagine that it's eventually something from the browser or the Graph.
One thing that comes to mind is when a `getRegistration` call ends up displaying 'name not registered' we could initiate a interval every 2 seconds or so that calls again to check if anything changed..

**Comment by cloudhead** [comment]
Yes I think that's a good solution.

I think the situation is simply racey, and the cache is on the server somewhere, since it loads correctly after a refresh. So retrying a couple of times when coming from the registration flow would be a good option.

**Comment by cloudhead** [comment]
Closed by #88
