### ISSUE TITLE
Small UI fixes

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#666]
Requested by @cloudhead.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/158411/230317584-f2f6773d-a961-42e4-8c1e-6255e3d97618.png">
<img width="715" alt="image (1)" src="https://user-images.githubusercontent.com/158411/230317592-9fde45d0-dea9-41c2-836c-8335d17e2efb.png">

Files without content don't have a placeholder.
<img width="1608" alt="Screenshot 2023-04-04 at 17 12 26" src="https://user-images.githubusercontent.com/158411/230318087-13e839b0-d42d-4c8e-b679-039ccfecdc1c.png">

**Comment by cloudhead** [comment]
Another one -- it should be possible to only select the code, without the lines:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/40774/230324776-29f18687-f7bf-492a-a71b-e9b5ff291b18.png">

**Comment by cloudhead** [comment]
Another,
<img width="665" alt="image" src="https://user-images.githubusercontent.com/40774/230399141-fefecbfa-1285-4c87-a476-64669ce70cff.png">

**Comment by cloudhead** [comment]
I'm also noticing that the UI is rendering `\n` as hard line breaks:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/40774/230402957-8b0b8190-86a4-4e83-b9fc-d4e4232fbca7.png">

Notice the line-break after "comment". This isn't right, as a line-break in markdown is a soft break that shouldn't affect the way the text is layed out.

**Comment by sebastinez** [comment]
Ok I think I addressed most of the mentioned issues.

Not sure on the "bump brightness" parts we currently use `foreground-5` which is a darker grey and then next step is `foreground-6` which is what we use for the highlighted parts.
<img width="174" alt="Bildschirmfoto 2023-04-13 um 10 45 48" src="https://user-images.githubusercontent.com/7912302/231705656-2330ee28-4a83-4966-88e3-ae479dbdbfaa.png">

So I'm thinking either we add more grey levels, or we remove the darker grey parts and make everything `foreground-6`

**Comment by sebastinez** [comment]
> Another, <img alt="image" width="665" src="https://user-images.githubusercontent.com/40774/230399141-fefecbfa-1285-4c87-a476-64669ce70cff.png">

This one seems to be an out of date state between the header and listing, when creating issues on the web we update the project header, but since we currently don't have patches creation implemented in the web, we don't know when to query for new patches..

Though not sure how the patch showed up in the listing.

Can you maybe elaborate, when/how you accessed the patch listing? Maybe you created a patch but didn't yet refresh the page?

**Comment by rudolfs** [comment]
> Ok I think I addressed most of the mentioned issues.
> 
> Not sure on the "bump brightness" parts we currently use `foreground-5` which is a darker grey and then next step is `foreground-6` which is what we use for the highlighted parts. <img alt="Bildschirmfoto 2023-04-13 um 10 45 48" width="174" src="https://user-images.githubusercontent.com/7912302/231705656-2330ee28-4a83-4966-88e3-ae479dbdbfaa.png">
> 
> So I'm thinking either we add more grey levels, or we remove the darker grey parts and make everything `foreground-6`

Yeah, you're right, we'd have to adjust the global level of that shade. Then also other parts of the app would be brighter. It looks fine on my monitor, I'd leave it as it is if it's up to me 🤷

**Comment by sebastinez** [comment]
Maybe we can do a general "subtitle" color for the teasers.
Something like this, I feel like it makes it more uniform and better readable
<img width="500" alt="Bildschirmfoto 2023-04-13 um 11 48 45" src="https://user-images.githubusercontent.com/7912302/231722325-65dada04-4800-4775-a4d2-c8669c2249ad.png">

Instead of 

<img width="512" alt="Bildschirmfoto 2023-04-13 um 11 52 56" src="https://user-images.githubusercontent.com/7912302/231723412-c9ed873a-1987-4e6d-a6c8-94a1652a7dbc.png">
