### ISSUE TITLE
Patch description shows up as revision

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#672]
See on this patch: https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches/59b37e8672d02a8ed2519fa7f746b42d6d05197f/59b37e8672d02a8ed2519fa7f746b42d6d05197f?state=open

The patch description is part of the Revision 0 comment, instead of being part of the patch itself; which means that when you have a second revision, you don't see the patch description anymore.

We should probably show the patch description under the title, like for the commit view.

**Comment by sebastinez** [comment]
Interesting, so usually we don't have a Revision 0 description since this is getting stored as the patch description.

So if we show the patch description under the title we won't have a Revision 0 comment anymore (or is there some way to create a patch description and a revision 0 comment together? Doesn't seem reasonable)

I'm for moving descriptions under the patch and issue title

**Comment by cloudhead** [comment]
I'd say the patch description goes under the patch title, and the revision descriptions go as comments?

**Comment by cloudhead** [comment]
On the CLI we don't allow setting a description for the initial revision. So that solves that problem I guess. It's a bit annoying to have to treat it differently but that's how we do it for now :shrug:

**Comment by cloudhead** [comment]
Would be good to prioritize this :) Patches with more than one revision basically don't show their description.

**Comment by sebastinez** [comment]
Will tackle this, to get a break from cli tooling
