### ISSUE TITLE
Proper footnotes in issues

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#725]
In markdown files, we have proper footnote support, but in comments, it doesn't look like it, see for eg.:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/40774/235173500-1f353766-d1be-4b7f-9377-00390875bd56.png">

https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/issues/7992b34d77f921f1976e7ee8dcf3cc4587845523

**Comment by sebastinez** [comment]
Hmm ok it seems that the issue here is that we defined correct footnote references as `[^0]` and the footer `[^0]: https://theupdateframework.github.io/specification/latest/` 

In this issue the footnote reference has been defined as `[0]` and the footer `[0]: https://theupdateframework.github.io/specification/latest/`

GitHub it seems like also uses `[^1]` as the correct way to define footnotes[^2]

[^2]: This is the footnote

**Comment by cloudhead** [comment]
Oh I see! In that case why does it create a link? It should show up like github, ie. it should just show [0] and the [0]: <footnote> should show up where the author placed it?

**Comment by cloudhead** [comment]
Hmm no it seems like github does the same as we do:

Testing[0] footnotes.

[0]: https://radicle.xyz

**Comment by cloudhead** [comment]
In that case I think we can close this. Maybe just make sure it works correctly with `[^0]` inside issues/comments etc.

**Comment by sebastinez** [comment]
Yeah I'll make sure to add a footnote example in the new CLI testing.
Tracking it with #748
