### ISSUE TITLE
Inconsistent monospace fonts

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#784]
I noticed that the font used in diffs is not the same as the one in commit messages. See:

<img width="677" alt="image" src="https://github.com/radicle-dev/radicle-interface/assets/40774/7a3e62cf-9a2e-429e-8b99-070765ecdf66">

One is `monospace`, and the other is `JetBrains Mono`. What's strange on my system is that those are supposed to be the same font, so I'm not sure why this is happening. But regardless, they should have the same CSS font family.

**Comment by rudolfs** [comment]
Should commit messages even be monospaced? I'm thinking of issue/patch descriptions usually being rendered as markdown. Shouldn't we apply the same rendering here? Especially because sometimes commit messages have code blocks. If we go this way, it would be weird to render the message monospace while still rendering markdown.

**Comment by sebastinez** [comment]
I think the idea behind using monospace is that it would be the same rendering you get when looking at it with `git log` in a shell.
But I understand what you mean, and I agree that code blocks and eventually even markdown would look much better.

For reference GitHub also shows the monospaced commit description
<img width="653" alt="Bildschirmfoto 2023-06-02 um 13 13 25" src="https://github.com/radicle-dev/radicle-interface/assets/7912302/14574966-e0a7-46cd-b13d-4348ff0ff8f6">
