### ISSUE TITLE
Request amplification bug on production

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#81]
Development:
![image](https://user-images.githubusercontent.com/40774/133985335-03faaa18-e606-4a77-b6f2-7a00074041eb.png)
Production:
![image](https://user-images.githubusercontent.com/40774/133985313-82788444-31e2-43f8-a323-307fdb08a447.png)

WTF

**Comment by sebastinez** [comment]
@cloudhead I used the `radicle-client-tools` project in production and discerned all requests to Alchemy to see what we were really calling.. It seems the duplicated queries are repeated calls to get the resolver of the namehash.. We could eventually pass it as part of the profile and avoid querying for every `getText`, or `getAddress`.
In development no queries are shown since they are being resolved over Metamask and do not show up in the browser developer console.
![Untitled Diagram](https://user-images.githubusercontent.com/7912302/134018817-9a9d6059-df83-437c-80e3-e465cfeb73a0.png)

It seems to me that in the end we can reduce the queries with a little optimization but it's not a problem of ethers and neither of vite.

**Comment by cloudhead** [comment]
Hmm interesting, yeah we can definitely cache stuff. I guess it makes sense that we wouldn't see them in Metamask! However I'm not sure why the queries are issued more than once? The svelte component doesn't appear to be rendered more than once, so I don't know where these requests are coming from..

**Comment by cloudhead** [comment]
Basically the avatar and seed host and address are fetched all at once, so the resolver shouldn't be fetched for each of those queries :thinking:

**Comment by sebastinez** [comment]
> Basically the avatar and seed host and address are fetched all at once, so the resolver shouldn't be fetched for each of those queries

IMO it seems that we are for the ENS information fetching everything separately, instead of together, since ethers creates one query for each `config.provider.getResolver(name)` and one for `resolver.getText('avatar')`
https://github.com/radicle-dev/radicle-interface/blob/a8fd990bfe4a8b561c447457be483b9ff71ccfbe/src/utils.ts#L250

With reducing the `getResolver` calls and parallelizing some ENS queries we can shave off some seconds from the loading time, but it seems that each query is required and not duplicated.

Here a comparison between the current state on the left and some optimizations on the right
![Screenshot from 2021-09-20 23-04-08](https://user-images.githubusercontent.com/7912302/134077467-4037d593-969a-45d8-81e9-835e90d03df8.png)

I think we could eventually create a PR to ethers that would allow us to pass a resolver as optional param and reduce another 2 queries eventually.
