### ISSUE TITLE
Description text not rendering <RID> and <OID>

### ISSUE THREAD

**Issue by xphoniex** [radicle-dev/radicle-interface#831]
Actual text:

![Screenshot from 2023-06-13 15-19-42](https://github.com/radicle-dev/radicle-interface/assets/14107758/22149c8c-a5d7-4adf-90a2-e503bd0b5eae)

Getting:

![Screenshot from 2023-06-13 15-18-59](https://github.com/radicle-dev/radicle-interface/assets/14107758/8e509244-1ad9-4855-a68a-e40895bb4ccb)

[Link](https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches/536a72783b7b0d2d3fe6e627ce0d3ba73923ba72?tab=activity)

**Comment by rudolfs** [comment]
This is resolved now.

<img width="724" alt="Screenshot 2023-06-26 at 13 20 22" src="https://github.com/radicle-dev/radicle-interface/assets/158411/1a9207da-754b-4c3c-88d7-744442e391f8">

**Comment by sebastinez** [comment]
So just wanted to follow up with this issue, since we reverted back with #888 and the text is not rendering again.
The way to do this so it works as a patch description is to use markdown code ticks in the commit message

---
This improves response time of:

- GET `/api/v1/projects/<RID>/tree/<OID>/from` 205.71ms down to 376.4µs
- GET `/api/v1/projects/<RID>/tree/<OID>/.nix` from 111.06ms down to 351.70µs
Also, CPU spike goes from 13.8% and 7.8% respectively down to 0.0%.

Signed-off-by: xphoniex [dj.2dixx@gmail.com](mailto:dj.2dixx@gmail.com)
