### ISSUE TITLE
Markdown comments are not parsed

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#883]
See this page:

https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/tree/master/radicle-cli/examples/rad-clone-all.md

The `<!-- TODO ... -->` comment should not show up in the doc.

**Comment by hecatia-elegua** [comment]
Hm, aren't you guys running the inputs through a sanitizer and then `marked`?
sth like `{@html sanitize(marked(rawData))}` would probably just work, maybe escaping `<RID>`

**Comment by sebastinez** [comment]
Hey @hecatia-elegua yeah we use `DOMPurify` and `marked` as you saw.

It would be awesome if by adding the tags we want to `DOMPurify` it would work out of the box, the issue is that we have some tags like `<RID>` and `<OID>` which aren't valid tags which we want to be displayed, so we need to escape them.

**Comment by hecatia-elegua** [comment]
@sebastinez After looking at #831 again, now I understand. These are not the only ones, all "custom tags" should just be escaped, since they're not supposed to be html elements, just e.g. visualization helpers. Man it would be easy if git commits were markdown.
