### ISSUE TITLE
Infer ts types from zod schema

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#911]
So I'm still learning about zod, but I started to think if we really need the typescript interfaces, besides the zod schemas.

And I stumbled upon the `z.infer` method which can be applied as follows
```ts
  public async createPatch(
    id: string,
    body: PatchCreate,
    authToken: string,
    options?: RequestOptions,
  ): Promise<z.infer<typeof patchCreatedSchema>> {
    return this.#fetcher.fetchOk(
      {
        method: "POST",
        path: `projects/${id}/patches`,
        headers: { Authorization: `Bearer ${authToken}` },
        body,
        options,
      },
      patchCreatedSchema,
    );
  }
```

This would allow us to reduce the amount of declared interfaces that we currently use to a minimum and where we only need the interface together with a schema we can infer the interface with `z.infer<typeof "zodSchema">`

**Comment by geigerzaehler** [comment]
When @rudolfs implemented this initially, it was me, I think, that suggested the current approach with the explicit Typescript interfaces and using `satisfies` on the schema declaration. My argument at the time was
1. Interfaces are more readable, so that when you want to understand what the response of `createPatch` is I prefer to look at the interface rather than the schema
2. Inferring the type messes with language server intellisense and produces incomprehensible type checking errors
3. There are “problems” when using `z.infer` with unions.

The last two points came mostly from my own anecdotal recollection, at the time, of working with zod. I’ve looked at this again and intellisense works fine, type checking errors are understandable and I couldn’t find or remember any of the problems with `z.infer`.

At this point in time, I also find 1. arguable. Schema definitions look different from Typescript interfaces so it requires a bit more cognitive effort to parse it. This is a tradeoff against having only one place where the shape is defined.

Today, I’d actually lean more towards using `z.infer` and I see no reason for you not to start using it. One thing that I would suggest is to still always declare response types from schemas so that you can export them.

```typescript
export type PatchCreated = z.infer<typeof patchCreatedSchema>

async createPatch(...): Promise<PatchCreated> { ... }
```

**Comment by sebastinez** [comment]
Thanks @geigerzaehler for the detailed answer.

Yeah I also think we shouldn't inline `z.infer` and I agree with declaring it as a response type.
I also think that the cognitive effort to parse it, is outweigh by having only one place of truth and reduce the amount of naming to be done.
